server.port: 8088

spring:
  datasource:
    url: jdbc:mysql://192.168.79.128:3306/hooscope?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.79.128
    port: 6379
    timeout: 5000
    database: 0

logging:
  config: classpath:logback.xml
  level:
    com.example.studyDemo.service: debug
